// Command docgen writes the reference pages in docs/reference from the code,
// so they can never drift from it: the HTTP routes, the container environment
// variables and the stored settings keys.
//
//	go run ./tools/docgen          rewrite docs/reference/*.md
//	go run ./tools/docgen -check   exit 1 if the files on disk are out of date (used by CI)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/rdborg/mediarium/internal/problems"
)

func main() {
	check := flag.Bool("check", false, "fail if the generated docs differ from what is on disk")
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	files := map[string][]byte{}
	api, err := apiDoc(*root)
	must(err)
	files["docs/reference/api.md"] = api
	env, err := envDoc(*root)
	must(err)
	files["docs/reference/environment.md"] = env
	set, err := settingsDoc(*root)
	must(err)
	files["docs/reference/settings-keys.md"] = set
	files["docs/reference/problem-codes.md"] = problemCodesDoc()

	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)

	stale := false
	for _, n := range names {
		path := filepath.Join(*root, filepath.FromSlash(n))
		want := normalize(files[n])
		if *check {
			got, _ := os.ReadFile(path)
			if !bytes.Equal(normalize(got), want) {
				fmt.Fprintf(os.Stderr, "out of date: %s\n", n)
				stale = true
			}
			continue
		}
		must(os.MkdirAll(filepath.Dir(path), 0o755))
		must(os.WriteFile(path, want, 0o644))
		fmt.Println("wrote", n)
	}
	if stale {
		fmt.Fprintln(os.Stderr, "Run `go run ./tools/docgen` and commit the result.")
		os.Exit(1)
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

func normalize(b []byte) []byte { return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n")) }

const banner = "<!-- Generated by `go run ./tools/docgen`. Do not edit by hand: change the code and regenerate. -->\n\n"

type route struct {
	Method, Path, Handler, Doc string
	Access                     string
}

// accessLabel names who may call a route, from the variable it is
// registered on in internal/api/server.go: public (signed out), member (any
// account) or admin.
func accessLabel(receiver string) string {
	switch receiver {
	case "public":
		return "**public**"
	case "member":
		return "any account"
	case "admin":
		return "admin"
	}
	return "signed in"
}

func apiDoc(root string) ([]byte, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, filepath.Join(root, "internal", "api"), func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	docs := map[string]string{}
	var routes []route
	for _, pkg := range pkgs {
		for _, f := range pkg.Files {
			for _, d := range f.Decls {
				if fn, ok := d.(*ast.FuncDecl); ok && fn.Doc != nil {
					docs[fn.Name.Name] = firstSentence(fn.Doc.Text(), fn.Name.Name)
				}
			}
			ast.Inspect(f, func(n ast.Node) bool {
				call, ok := n.(*ast.CallExpr)
				if !ok || len(call.Args) != 2 {
					return true
				}
				sel, ok := call.Fun.(*ast.SelectorExpr)
				if !ok || sel.Sel.Name != "HandleFunc" {
					return true
				}
				recv, _ := sel.X.(*ast.Ident)
				lit, ok := call.Args[0].(*ast.BasicLit)
				if !ok || recv == nil {
					return true
				}
				pattern, _ := strconv.Unquote(lit.Value)
				method, path, found := strings.Cut(pattern, " ")
				if !found || !strings.HasPrefix(path, "/api") {
					return true
				}
				h := ""
				if hs, ok := call.Args[1].(*ast.SelectorExpr); ok {
					h = hs.Sel.Name
				}
				routes = append(routes, route{Method: method, Path: path, Handler: h, Access: accessLabel(recv.Name)})
				return true
			})
		}
	}
	for i := range routes {
		routes[i].Doc = docs[routes[i].Handler]
	}
	sort.Slice(routes, func(i, j int) bool {
		gi, gj := group(routes[i].Path), group(routes[j].Path)
		if gi != gj {
			return gi < gj
		}
		if routes[i].Path != routes[j].Path {
			return routes[i].Path < routes[j].Path
		}
		return routes[i].Method < routes[j].Method
	})

	var b strings.Builder
	b.WriteString("# HTTP API reference\n\n" + banner)
	b.WriteString("Every route the server exposes. Routes marked **public** need no sign-in; all others need a session cookie or an `X-API-Key` header (see the Profile page). Routes marked **any account** work for members and administrators; routes marked **admin** answer members with 403 `{\"error\": \"Only an administrator can do this.\"}` (see [accounts.md](../accounts.md)). Responses are JSON; errors are `{\"error\": \"...\"}`.\n\n")
	last := ""
	for _, r := range routes {
		g := group(r.Path)
		if g != last {
			fmt.Fprintf(&b, "\n## %s\n\n| Method | Path | Access | What it does |\n|---|---|---|---|\n", g)
			last = g
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", r.Method, r.Path, r.Access, strings.ReplaceAll(r.Doc, "|", "\\|"))
	}
	fmt.Fprintf(&b, "\n%d routes.\n", len(routes))
	return []byte(b.String()), nil
}

func group(path string) string {
	p := strings.TrimPrefix(path, "/api/")
	seg, _, _ := strings.Cut(p, "/")
	if seg == "" {
		return "general"
	}
	return seg
}

func firstSentence(doc, name string) string {
	doc = strings.TrimSpace(strings.ReplaceAll(doc, "\n", " "))
	doc = strings.TrimPrefix(doc, name+" ")
	if i := strings.Index(doc, ". "); i > 0 {
		doc = doc[:i+1]
	}
	if strings.Contains(doc, "PRD") || strings.Contains(doc, "CLAUDE") {
		return "" // internal planning references do not belong in public docs
	}
	if len(doc) > 160 {
		doc = doc[:157] + "..."
	}
	return doc
}

func envDoc(root string) ([]byte, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filepath.Join(root, "internal", "config", "config.go"), nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	type env struct{ Name, Default string }
	var vars []env
	ast.Inspect(f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok || len(call.Args) != 2 {
			return true
		}
		id, ok := call.Fun.(*ast.Ident)
		if !ok || (id.Name != "envStr" && id.Name != "envInt") {
			return true
		}
		k, ok1 := call.Args[0].(*ast.BasicLit)
		d, ok2 := call.Args[1].(*ast.BasicLit)
		if ok1 && ok2 {
			name, _ := strconv.Unquote(k.Value)
			def := d.Value
			if u, err := strconv.Unquote(def); err == nil {
				def = u
			}
			vars = append(vars, env{name, def})
		}
		return true
	})
	sort.Slice(vars, func(i, j int) bool { return vars[i].Name < vars[j].Name })
	var b strings.Builder
	b.WriteString("# Environment variables\n\n" + banner)
	b.WriteString("Container-level settings only. Everything else (indexers, Usenet servers, naming, VPN, notifications) is set in the app under Settings, not here. `PUID`, `PGID` and `TZ` are read by the container entrypoint, not by the app.\n\n| Variable | Default |\n|---|---|\n")
	for _, v := range vars {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", v.Name, v.Default)
	}
	b.WriteString("| `PUID` | `1000` |\n| `PGID` | `1000` |\n| `TZ` | `Etc/UTC` |\n")
	return []byte(b.String()), nil
}

func settingsDoc(root string) ([]byte, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filepath.Join(root, "internal", "settings", "settings.go"), nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	type key struct{ Const, Value, Note string }
	var keys []key
	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			for i, name := range vs.Names {
				if !strings.HasPrefix(name.Name, "Key") || i >= len(vs.Values) {
					continue
				}
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok {
					continue
				}
				val, _ := strconv.Unquote(lit.Value)
				note := ""
				if vs.Comment != nil {
					note = strings.TrimSpace(strings.TrimPrefix(vs.Comment.Text(), "//"))
				}
				keys = append(keys, key{name.Name, val, strings.ReplaceAll(note, "\n", " ")})
			}
		}
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i].Value < keys[j].Value })
	var b strings.Builder
	b.WriteString("# Stored settings\n\n" + banner)
	b.WriteString("The keys the app stores in its settings table. You normally change these from the Settings pages, not directly. Values marked encrypted are stored encrypted with the key in `secret.key`.\n\n| Key | Notes |\n|---|---|\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "| `%s` | %s |\n", k.Value, strings.ReplaceAll(k.Note, "|", "\\|"))
	}
	return []byte(b.String()), nil
}

// problemCodesDoc lists every code of the problem log with its plain-language
// help, straight from the table the app uses (internal/problems).
func problemCodesDoc() []byte {
	var b strings.Builder
	b.WriteString("# Problem codes\n\n" + banner)
	b.WriteString("Every problem on Settings > System > Logs and errors has one of these codes. The words are the same as on the page. A problem with a code that is not listed here shows its own message and technical detail. See [Logs and errors](../logs-and-errors.md).\n\n")
	cell := func(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
	for _, area := range problems.Areas() {
		var rows []problems.Help
		for _, h := range problems.Catalog() {
			if h.Area == area.ID {
				rows = append(rows, h)
			}
		}
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n| Code | Level | What it means | What to try | Where |\n|---|---|---|---|---|\n", area.Label)
		for _, h := range rows {
			where := ""
			if h.LinkPath != "" {
				where = "`" + h.LinkPath + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | **%s.** %s | %s | %s |\n", h.Code, h.Level, cell(h.Title), cell(h.Explain), cell(h.Try), where)
		}
		b.WriteString("\n")
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}
